### PR TITLE
fix: Forge Detection logging if you don't have the required items.

### LINKED ISSUE #11: [Bug] Forged Transaction logs even tho you dont have the materials to forge the item
grafik

### PR DESCRIPTION
**Pull request by jani270**
Closes #11

### CODE REVIEW

File: mod/src/main/kotlin/moe/nea/ledger/modules/ForgeDetection.kt [hunk 1]
```diff
@@ -21,6 +21,7 @@ class ForgeDetection {
 		val slot = event.slotIn ?: return
 		val clickedItem = slot.stack ?: return
 		if (clickedItem.displayName.unformattedString() != "Confirm") return
+		if (clickedItem.itemDamage == 14) return
```
Comment (lineargraph) [inline mod/src/main/kotlin/moe/nea/ledger/modules/ForgeDetection.kt]: Can you use `EnumDyeColor.byDyeDamage` (or the corresponding method for the item type here)

**Review by lineargraph — CHANGES_REQUESTED** [review]

**Review by lineargraph — APPROVED** [review]
